### ISSUE TITLE
Naming of results file name

### ISSUE THREAD

**Issue by attesn** [webbidevaajat/tramhfp#4]
Was thinking that result file name could be self-explanatory. For example `links_times_shp`  could be `fname_links_results`

**Comment by jmutikainen** [comment]
I can definitely change the variable name in the code, but do you mean the default value ("links_times.shp") as well? In latter case, I'm not sure what the name should be and it could be confusing if it changes for the user after the R education. @atte-wsp

**Comment by attesn** [comment]
Probably just parameter name. I'd think that when writing the function it's more clear to write `run_all(fname_results = "name")` than  `run_all(links_times_shp = "name")`

**Comment by jmutikainen** [comment]
Closed by latest pull.
