### ISSUE TITLE
Distance to cut points

### ISSUE THREAD

**Issue by attesn** [webbidevaajat/tramhfp#5]
https://github.com/webbidevaajat/tramhfp/blob/1389d12874a673dc3bb33a629e5adf4af0c9e571/R/link_id_to_hfp.R#L42

This cuts point further than 30 meter away from line. However, based on raw HFP data 50 meters could be more suitable distance. For some reason coordinates are some times jumping quite much

**Comment by jmutikainen** [comment]
Closed by latest pull.
