### ISSUE TITLE
Start - end time filtering

### ISSUE THREAD

**Issue by attesn** [webbidevaajat/tramhfp#6]
https://github.com/webbidevaajat/tramhfp/blob/1389d12874a673dc3bb33a629e5adf4af0c9e571/R/link_stats.R#L50

This is one issue that could cause invalid link observations. This filters HFP observations based on time, which may cause point sequence to be cut in middle of trip or link. 

Could this be replaced filtering with `start_time_date` of trip, so it we would always have observations for whole trip from start to end stop

**Comment by jmutikainen** [comment]
I think we need to hear our clients' opinion on this before we do such a change to filtering. This could prevent one invalid link observation per day per route but also make it harder to control the desired time period.
